### ISSUE TITLE
clojurecl speed compared with native c++

### ISSUE THREAD

**Issue by zcaudate** [uncomplicate/clojurecl#16]
I'm curious to know if there are any benchmarks for operations in clojurecl as compared to using c++.

I've done my own benchmarking with the opencv ocl library and clojurecl on a custom image algorithm and found that there is an order of an magnitude difference between jocl and native ocl:

jocl, 0250px: 2.467 ms
jocl, 0500px: 6.367 ms
jocl, 1000px: 24.060 ms
jocl, 2000px: 81.356 ms
jocl, 4000px: 287.928 ms
jocl, 8000px: 1031.693 ms

cv::ocl, 0250px: 0.475 ms
cv::ocl, 0500px: 0.783 ms
cv::ocl, 1000px: 1.632 ms
cv::ocl, 2000px: 4.555 ms
cv::ocl, 4000px: 15.846 ms
cv::ocl, 8000px: 121.899 ms

The only reason I can think of is the buffer copy of the java BufferedImage data vs some special thing that the opencv UMat structure has. Would there be other reasons?

**Comment by blueberry** [comment]
Hi Chris,

Did you use ClojureCL there, or JOCL directly?
Also, JOCL/ClojureCL are general libraries, while OpenCV is specialized for images. It is difficult to say why are you seeing such a great difference without looking at the code.

In my experience, there is no noticeable difference that matter in *equivalent* code.

**Comment by zcaudate** [comment]
Thanks Dragan

I’m using clojurecl but compiling the same *.cl code that is being used by opencv.

I’ll put together something that demonstrates this so you can have a look.

**Comment by blueberry** [comment]
@zcaudate Chris, have you resolved this issue?

**Comment by zcaudate** [comment]
@blueberry: It is kind of resolved. It's to do with work group size but there are some strange behavioural issues. I still need to upload an example. Will do that by week's end.

**Comment by zcaudate** [comment]
@blueberry: please have a look at: https://github.com/zcaudate-me/image-bench

the local size is adjustable on c++ (can test by running `bin/sobel_benchmark`) but not on [jocl](https://github.com/zcaudate-me/image-bench/blob/master/source/clojure/image_bench/sobel.clj#L28). It results in weird errors which I've documented on the readme.

**Comment by blueberry** [comment]
@zcaudate It seems to me that the original issue (speed) has been resolved, and that now you have different issue regarding controlling work sizes. 

Can you please create a *minimal* example that demonstrates the invalid work group size error that you're getting. I glanced over that repository, but there are hundreds of lines of code, and the issue might easily be that you're simply calling a work group configuration that your hardware or drivers do not support, or that even do not make much sense (such was the original issue that was caused by calling kernels with work group dimensions 1x1.

The most common case of the exception you reported is when a code constructs work group whose global size is not an integer multiple of work group size. This is supported in OpenCL 2.0, but not allowed in OpenCL 1.2.

I'll close *this* issue now. Feel free to open *another* issue about to working group sizes.

**Comment by zcaudate** [comment]
Thanks. I've opened a new issue.

To be fair, this code is pretty minimal. The main kernel code is in [sobel.clj](https://github.com/zcaudate-me/image-bench/blob/master/source/clojure/image_bench/sobel.clj) and the three functions are pretty much identical.

The other code is my attempt at cpp and verifying that the pixel values are the same when opened by different platforms. Believe it or not, [pixel values vary](https://stackoverflow.com/questions/48678390/pixel-value-differences-between-opencv-and-java).
