### ISSUE TITLE
Any clue on running on Mac OS X?

### ISSUE THREAD

**Issue by neolee** [uncomplicate/clojurecl#4]
Followed instruction on http://clojurecl.uncomplicate.org/articles/getting_started.html and successful started the REPL. But error when trying to load uncomplicate.clojurecl using ns:

user=> (ns example (:use [uncomplicate.clojurecl core info]))
CompilerException java.lang.UnsatisfiedLinkError: Error while loading native library "JOCL_0_2_0-apple-x86_64" with base name "JOCL_0_2_0"
Operating system name: Mac OS X
Architecture         : x86_64
Architecture bit size: 64

Should I install JOCL manually? And any suggested guide to do that? I'm familiar with clojure and java but not OpenCL.

Thanks for the work!

**Comment by blueberry** [comment]
For now, you'll have to build jocl library yourself. Since osx supplies opencl out of the box it requires some experimenting since jocl needs opencl 2.0 headers, while apple still ships 1.2. it is a c library, no opencl knowledge needed.

There is a discussion at http://forum.byte-welt.net/byte-welt-projekte-projects/swogl-jcuda-jocl/jocl/15575-jocl-0-2-0-available-maven.html
where you can ask the author for help with the details. The problem is that none of the power users of jocl has a mac, otherwise it would already be in maven central.

Please, when you build jocl, contact marco (the author) to include it in the official distribution.

I plan to solve that issue myself eventually, but it won't be on the table for at least several months.

**Comment by blueberry** [comment]
@neolee Both ClojureCL and Neanderthal OpenCL GPU engine will work on Macs out of the box soon. I have already implemented everything and am waiting for the release of dependencies.

**Comment by blueberry** [comment]
Release 0.6.0 and higher support OS X out of the box.
