### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by birdspider** [uncomplicate/clojurecl#9]
following 'http://clojurecl.uncomplicate.org/articles/getting_started.html#usage' I accountered the following problem:

```
user=> (use '[uncomplicate.clojurecl core info])

; (first (devices (first (platforms)))) 
;  prints: #object[org.jocl.cl_device_id 0x74f98b81 "cl_device_id[0x7f2488893658]"])

user=> (info (first (devices (first (platforms)))))

StringIndexOutOfBoundsException String index out of range: -1
        java.lang.String.checkBounds (String.java:381)
        java.lang.String.<init> (String.java:545)
        uncomplicate.clojurecl.info/built-in-kernels (info.clj:302)
        uncomplicate.clojurecl.info/built-in-kernels (info.clj:301)
        uncomplicate.clojurecl.info/eval15681/fn--15682/fn--15688 (info.clj:785)
        uncomplicate.clojurecl.info/eval15681/fn--15682 (info.clj:785)
        uncomplicate.clojurecl.info/eval14856/fn--14857/G--14847--14866 (info.clj:232)
        user/eval17172 (form-init3078489940360833927.clj:1)
        user/eval17172 (form-init3078489940360833927.clj:1)
        clojure.lang.Compiler.eval (Compiler.java:6927)
        clojure.lang.Compiler.eval (Compiler.java:6890)
        clojure.core/eval (core.clj:3105)
```

archlinux
 intel-opencl-sdk (2016-5)
 intel-opencl-runtime (1:16.1-2)

**Comment by blueberry** [comment]
Can you please try other separate info functions from the `info` namespace and post the result here? 

The problem might be that Intel's platform does not support some OpenCL standard functions well (although ClojureCL should catch that and wrap it into report inside other information - are you sure that you pasted the COMPLETE stack trace?)

If it is only `built-in-kernels` that creates problems, you should still be able to use ClojureCL until we find what is the problem here.

**Comment by blueberry** [comment]
I found the bug and the patched release will be released quickly.

**Comment by birdspider** [comment]
great ! no hurry, I just tested it out of curiosity

**Comment by blueberry** [comment]
no problem, even if you don't need and it is a minor issue someone else might need it working properly ;)

**Comment by birdspider** [comment]
there are followup errors, do you want them here or in a new issue ?

**Comment by blueberry** [comment]
New issue.
